### ISSUE TITLE
add @Deprecated annotation for deprecated OpenAPI endpoint & property

### ISSUE THREAD

**Issue by schlagi123** [openapi-processor/openapi-processor-spring#113]
Hi,

If I use the open-api deprecated attribute in a method or in a model, I want to have a @Deprecated annotation in the generated code.

**Comment by hauner** [comment]
depends on openapi-processor/openapi-processor-core#10

**Comment by schlagi123** [comment]
openapi-processor/openapi-processor-core#10 fixed with ticket
