### ISSUE TITLE
writeOnly fields are not marked as such in the generated DTO

### ISSUE THREAD

**Issue by davidjohnstonverint** [openapi-processor/openapi-processor-spring#136]
If I mark a field in the open API spec as writeOnly: true, e.g. as you might do for a password/token:

    accessToken:
    type: string
    writeOnly: true

The generated DTO class does not mark the field as write only. Ideally it would mark the field on the DTO with JsonProperty.Access.WRITE_ONLY in the @JsonProperty annotation

**Comment by hauner** [comment]
This should be easy to implement, looking at it.

Thanks for the feedback. :-)
