### ISSUE TITLE
missing import for javax.validation.constraints.Pattern

### ISSUE THREAD

**Issue by kugelstachelfisch** [openapi-processor/openapi-processor-spring#141]
Hi there, thanks for the great job!
I've found a minor issue:

When array-elements of type string are described by a pattern and the array is mapped to java.util.List, the import for @Pattern-Annotation is missing.

I've tested with openapi-processor-spring V2022.3.

A minimal testcase is attached. Without the line `import javax.validation.constraints.Pattern;`, the test runs successfully, but the import is required to compile.

[list-pattern-missing-import.zip](https://github.com/openapi-processor/openapi-processor-spring/files/8708327/list-pattern-missing-import.zip)

**Comment by hauner** [comment]
yep, looks like a bug. Thanks for test-case :-)

**Comment by hauner** [comment]
fix is available in openapi-processor-spring 2022.4
