### ISSUE TITLE
Maven plugin with spring 2023.1 fails

### ISSUE THREAD

**Issue by aburmeis** [openapi-processor/openapi-processor-spring#154]
I just tried to upgrade to 2023.1 using maven plugin 2021.1. I get the following error message from maven:

`[ERROR] Failed to execute goal io.openapiprocessor:openapi-processor-maven-plugin:2021.1:process (spring) on project berlinalx: Execution spring of goal io.openapiprocessor:openapi-processor-maven-plugin:2021.1:process failed: Plugin io.openapiprocessor:openapi-processor-maven-plugin:2021.1 or one of its dependencies could not be resolved: Failed to collect dependencies at io.openapiprocessor:openapi-processor-maven-plugin:jar:2021.1 -> io.openapiprocessor:openapi-processor-spring:jar:2023.1 -> io.openapiprocessor:openapi-processor-core:jar:2023.1: Failed to read artifact descriptor for io.openapiprocessor:openapi-processor-core:jar:2023.1: io.openapiprocessor:openapi-parser-bom:pom:2022.2-SNAPSHOT was not found in https://dl.bintray.com/openapi-processor/primary during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of bintray.obsolete has elapsed or updates are forced`

To be honest, I cannot find any 2023 release of core...

**Comment by hauner** [comment]
grmpf, looks like i messed up the dependencies. Looking at it...

**Comment by hauner** [comment]
fixed in 2023.1.1.

Thanks for reporting :-)
