### ISSUE TITLE
'head' and 'options' mapping produces bad imports

### ISSUE THREAD

**Issue by beeondev** [openapi-processor/openapi-processor-spring#192]
Hi,

It seem that  'head' and 'options' mapping just not compile because :
-   Some unused import just not exist in spring-web : 
         import org.springframework.web.bind.annotation.HeadMapping;
         import org.springframework.web.bind.annotation.OptionsMapping;
- Some import are never declared :
       import org.springframework.web.bind.annotation.RequestMapping;
       import org.springframework.web.bind.annotation.RequestMethod;

[options-and-head-mapping.ZIP](https://github.com/openapi-processor/openapi-processor-spring/files/12594789/options-and-head-mapping.ZIP)

So for the moment i end up with just a workaround to exclude thoses endpoint. 
First, i try with "exclude" mapping directive, but i realize that it is useless, because the mapping still generated (with another name as explained in documentation). I finally exclude it from openapi.yaml spec.

best regards.

**Comment by hauner** [comment]
I can reproduce the issue, it is broken. 

there is code that tries to handle this but looks a bit strange. Too bad the corresponding test doesn't include head, options and trace examples. oops.

Thanks for reporting!
