### ISSUE TITLE
Don't add @JsonProperty annotation (configurable)

### ISSUE THREAD

**Issue by mjparme** [openapi-processor/openapi-processor-spring#268]
It would be nice if there was a configuration option available so we could avoid the redundant `@JsonProperty` annotation. There is simply no need for the annotation when the value in the annotation is the same as the name of the field. Example:

```java
  @JsonProperty("suffix")
  String suffix
```

This is simply redundant.

**Comment by hauner** [comment]
Yes it is redundant. It was just simpler to add it always instead of checking first if the value is a valid java identifier. :wink: 

I guess it is not too hard to add now with the latest improvements to the identifier handling.

**Comment by hauner** [comment]
Maybe this does not need an option. It could auto-detect if the name is a valid identifier (or has set the `readOnly`/`writeOnly`property) and just add `@JsonProperty` when it is needed.
