### ISSUE TITLE
How to genearte code with multiple OAS yaml files?

### ISSUE THREAD

**Issue by RobinQu** [openapi-processor/openapi-processor-spring#284]
It seems all examples are working with only one OAS yaml file.

**Comment by hauner** [comment]
you are looking for something like this?

https://github.com/openapi-processor/openapi-processor-gradle/releases/tag/v2022.1

**Comment by RobinQu** [comment]
> you are looking for something like this?
> 
> https://github.com/openapi-processor/openapi-processor-gradle/releases/tag/v2022.1

Yes. 

But does maven plugin has same capability?

**Comment by hauner** [comment]
Yes, this also works with the maven plugin. Here is an example:

https://github.com/openapi-processor/openapi-processor-samples/blob/master/samples/spring-multiple-apis/pom.xml

**Comment by RobinQu** [comment]
Oh, I see. Thanks for your help.
