### ISSUE TITLE
Missing openapi spec for 200 response content silently drops interface method from generation

### ISSUE THREAD

**Issue by eekboom** [openapi-processor/openapi-processor-spring#287]
most of the end points defined in out `openapi.yaml` have a section like this one:

````
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
````

Accidentally one of our operations in the `openapi.yaml` was missing the definition for response 200.
openapi-processor just silently skipped the operation and generated an empty interface instead.

I don't know what the best/correct result would be here, but I propose to at least add an error message to the log and/or generate the interface method with void return type.

**Comment by hauner** [comment]
I think a warning about the empty interface could be helpful.

**Comment by hauner** [comment]
next release will report this situation with `endpoint '/foo' has no success 2xx response.`
